/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServerNameDialog.java
 *
 * Created on Aug 4, 2009, 1:43:45 PM
 */

package amltpvcocina;




/**
 *
 * @author pc-xp1
 */
public class ServerNameDialog extends javax.swing.JDialog {

    /** Creates new form ServerNameDialog */
    public ServerNameDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String persistedServer = Main.persister.operator.retrieveValue("servidor");
        if (persistedServer.equals("error")){
            Main.persister.operator.newSetting("servidor", "Escriba");
        }
        serverNameField.setText(Main.persister.operator.retrieveValue("servidor"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverNameField = new javax.swing.JTextField();
        conectarButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Introduca el nombre del servidor");

        serverNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverNameFieldActionPerformed(evt);
            }
        });

        conectarButton.setText("Conectar");
        conectarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(serverNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(conectarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serverNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conectarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conectarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarButtonActionPerformed
        Main.serverName = serverNameField.getText();
        Thread conexionThread = new Thread(new ThreadNetworking());
        conexionThread.start();
        Main.persister.operator.updateSetting("servidor", Main.serverName);
        this.dispose();
    }//GEN-LAST:event_conectarButtonActionPerformed

    private void serverNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverNameFieldActionPerformed
        conectarButtonActionPerformed(evt);
    }//GEN-LAST:event_serverNameFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton conectarButton;
    private javax.swing.JTextField serverNameField;
    // End of variables declaration//GEN-END:variables

}
